### ISSUE TITLE
error fixed please

### ISSUE THREAD

**Issue by drakgons** [FashionCStar/youtube-scrape#1]
Can you solve this problem please:

sectionList.itemSectionRenderer.contents.forEach(content => {
                                                        ^

TypeError: Cannot read property 'contents' of undefined
    at C:\Users\Fox\Desktop\nodejs\youtube-scrape\scraper.js:34:57
    at Array.forEach (<anonymous>)
    at Request._callback (C:\Users\Fox\Desktop\nodejs\youtube-scrape\scraper.js:33:34)
    at Request.self.callback (C:\Users\Fox\Desktop\nodejs\youtube-scrape\node_modules\request\request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (C:\Users\Fox\Desktop\nodejs\youtube-scrape\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (C:\Users\Fox\Desktop\nodejs\youtube-scrape\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)

**Comment by FashionCStar** [comment]
add this code

```
if (sectionList.itemSectionRenderer) {
..........
}
```
